apiVersion: apps/v1 # Menentukan versi API yang digunakan untuk Deployment
kind: Deployment # Menentukan jenis resource, dalam hal ini Deployment
metadata:
  name: shipping-service # Menentukan nama Deployment sebagai "shipping-service"
spec:
  replicas: 1 # Menentukan jumlah replika pod yang harus dijalankan (hanya 1 instance)
  selector:
    matchLabels:
      app: shipping-service # Menentukan label selector untuk mencocokkan pod yang dikelola oleh Deployment
  template:
    metadata:
      labels:
        app: shipping-service # Menetapkan label "app: shipping-service" untuk pod
    spec:
      containers:
        - name: shipping-service # Menentukan nama container sebagai "shipping-service"
          image: ghcr.io/abiyamakruf/shipping-service:latest # Menentukan image dari container dengan versi terbaru dari GitHub Container Registry
          ports:
            - containerPort: 3001 # Mengekspos port 3001 pada container
          # Bisa menggunakan cara berikut atau menggunakan .env pada masing-masing container (namun karena url berubah-berubah dan menganti image akan lama lebih baik disini)
          env:
            - name: AMQP_URL # Menetapkan variabel lingkungan untuk koneksi ke RabbitMQ
              value: "amqp://guest:guest@rabbitmq:5672" # URL untuk menghubungkan service ke RabbitMQ

---
apiVersion: v1 # Menentukan versi API yang digunakan untuk Service
kind: Service # Menentukan jenis resource, dalam hal ini Service
metadata:
  name: shipping-service # Menentukan nama Service sebagai "shipping-service"
spec:
  selector:
    app: shipping-service # Memilih pod dengan label "app: shipping-service" untuk dikaitkan dengan Service
  ports:
    - protocol: TCP # Menggunakan protokol TCP
      port: 3001 # Mengekspos port 3001 pada Service
      targetPort: 3001 # Mengarahkan permintaan ke port 3001 pada pod
  type: ClusterIP # Menentukan tipe Service sebagai ClusterIP (hanya dapat diakses dalam cluster)
